# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

archives_base_name=BetterF3

minecraft_version=1.21.3
supported_minecraft_versions=1.21.2/1.21.3
supported_minecraft_versions_list=1.21.2,1.21.3

mod_version=12.0.0
releaseType=release
maven_group=me.treyruffy.betterf3

platforms=fabric,neoforge,forge

fabric_loader_version=0.16.9
fabric_api_version=0.107.0+1.21.3

cloth_version=16.0.141
modmenu_version=12.0.0-beta.1

forge_version=53.0.7
neoforge_version=21.3.10-beta

modrinth_id=8shC1gFX
curseforge_id=401648
